// <auto-generated />
using DotNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DotNetCore.Migrations
{
    [DbContext(typeof(ParkContext))]
    partial class ParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCore.Models.Park", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<decimal>("costPerHouser");

                    b.HasKey("ID");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("DotNetCore.Models.Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End");

                    b.Property<int>("ParkID");

                    b.Property<int>("PlaceID");

                    b.Property<DateTime>("Start");

                    b.HasKey("ID");

                    b.HasIndex("ParkID");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("DotNetCore.Models.Place", b =>
                {
                    b.HasOne("DotNetCore.Models.Park", "Park")
                        .WithMany()
                        .HasForeignKey("ParkID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
